# Generated by Django 3.1.3 on 2020-11-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=15),
        ),
    ]
