# Generated by Django 3.1.3 on 2020-11-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_auto_20201116_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
