# Generated by Django 3.1.3 on 2020-11-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0005_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
